// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayGamesConstants
{
        public const string achievement_mastery__commitment = "CgkI3tmTz-kLEAIQEA"; // <GPGSID>
        public const string achievement_equilibrium__stage_2 = "CgkI3tmTz-kLEAIQCA"; // <GPGSID>
        public const string achievement_chaos__hydra = "CgkI3tmTz-kLEAIQAw"; // <GPGSID>
        public const string achievement_equilibrium__stage_1 = "CgkI3tmTz-kLEAIQBw"; // <GPGSID>
        public const string achievement_harmony__centaurus = "CgkI3tmTz-kLEAIQAQ"; // <GPGSID>
        public const string achievement_equilibrium__stage_3 = "CgkI3tmTz-kLEAIQCQ"; // <GPGSID>
        public const string achievement_equilibrium__stage_4 = "CgkI3tmTz-kLEAIQCg"; // <GPGSID>
        public const string achievement_mastery__rotation = "CgkI3tmTz-kLEAIQCw"; // <GPGSID>
        public const string achievement_mastery__multicolor = "CgkI3tmTz-kLEAIQDg"; // <GPGSID>
        public const string achievement_learner = "CgkI3tmTz-kLEAIQAA"; // <GPGSID>
        public const string achievement_mastery__limitations = "CgkI3tmTz-kLEAIQDQ"; // <GPGSID>
        public const string achievement_chaos__centaurus = "CgkI3tmTz-kLEAIQBQ"; // <GPGSID>
        public const string achievement_harmony__hydra = "CgkI3tmTz-kLEAIQAg"; // <GPGSID>
        public const string achievement_supporter = "CgkI3tmTz-kLEAIQDw"; // <GPGSID>
        public const string achievement_mastery__fusion = "CgkI3tmTz-kLEAIQDA"; // <GPGSID>
        public const string achievement_mastery__curiousness = "CgkI3tmTz-kLEAIQEQ"; // <GPGSID>

}

